apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:                       # Fix the typo here from "posts" to "ports"
    - port: 5000
      targetPort: 5000
      protocol: TCP
